#ifndef WIFI_CONFIG_H
#define WIFI_CONFIG_H

// Define WiFi configuration macros that might be missing
#ifndef CONFIG_ESP_WIFI_STATIC_RX_BUFFER_NUM
#define CONFIG_ESP_WIFI_STATIC_RX_BUFFER_NUM 10
#endif

#ifndef CONFIG_ESP_WIFI_DYNAMIC_RX_BUFFER_NUM
#define CONFIG_ESP_WIFI_DYNAMIC_RX_BUFFER_NUM 32
#endif

#ifndef CONFIG_ESP_WIFI_TX_BUFFER_TYPE
#define CONFIG_ESP_WIFI_TX_BUFFER_TYPE 1
#endif

#ifndef WIFI_STATIC_TX_BUFFER_NUM
#define WIFI_STATIC_TX_BUFFER_NUM 16
#endif

#ifndef WIFI_DYNAMIC_TX_BUFFER_NUM
#define WIFI_DYNAMIC_TX_BUFFER_NUM 32
#endif

#ifndef CONFIG_ESP_WIFI_DYNAMIC_RX_MGMT_BUF
#define CONFIG_ESP_WIFI_DYNAMIC_RX_MGMT_BUF 1
#endif

#ifndef WIFI_RX_MGMT_BUF_NUM_DEF
#define WIFI_RX_MGMT_BUF_NUM_DEF 32
#endif

#ifndef WIFI_CACHE_TX_BUFFER_NUM
#define WIFI_CACHE_TX_BUFFER_NUM 32
#endif

#ifndef WIFI_CSI_ENABLED
#define WIFI_CSI_ENABLED 0
#endif

#ifndef WIFI_AMPDU_RX_ENABLED
#define WIFI_AMPDU_RX_ENABLED 1
#endif

#ifndef WIFI_AMPDU_TX_ENABLED
#define WIFI_AMPDU_TX_ENABLED 1
#endif

#ifndef WIFI_AMSDU_TX_ENABLED
#define WIFI_AMSDU_TX_ENABLED 0
#endif

#ifndef WIFI_NVS_ENABLED
#define WIFI_NVS_ENABLED 1
#endif

#ifndef WIFI_NANO_FORMAT_ENABLED
#define WIFI_NANO_FORMAT_ENABLED 0
#endif

#ifndef WIFI_DEFAULT_RX_BA_WIN
#define WIFI_DEFAULT_RX_BA_WIN 16
#endif

#ifndef WIFI_TASK_CORE_ID
#define WIFI_TASK_CORE_ID 0
#endif

#ifndef WIFI_SOFTAP_BEACON_MAX_LEN
#define WIFI_SOFTAP_BEACON_MAX_LEN 752
#endif

#ifndef WIFI_MGMT_SBUF_NUM
#define WIFI_MGMT_SBUF_NUM 32
#endif

#ifndef WIFI_FEATURE_CAPS
#define WIFI_FEATURE_CAPS 0
#endif

#ifndef WIFI_STA_DISCONNECTED_PM_ENABLED
#define WIFI_STA_DISCONNECTED_PM_ENABLED 0
#endif

#ifndef CONFIG_ESP_WIFI_ESPNOW_MAX_ENCRYPT_NUM
#define CONFIG_ESP_WIFI_ESPNOW_MAX_ENCRYPT_NUM 7
#endif

// Newer ESP-IDF configurations
#ifndef WIFI_TX_HETB_QUEUE_NUM
#define WIFI_TX_HETB_QUEUE_NUM 1
#endif

#ifndef WIFI_DUMP_HESIGB_ENABLE
#define WIFI_DUMP_HESIGB_ENABLE 0
#endif

#endif // WIFI_CONFIG_H
